### ISSUE TITLE
Fuzz deserialization and serialization

### ISSUE THREAD

**Issue by pyfisch** [enarx/ciborium#11]
First of all: Thanks for making this crate! I know there is a lot of demand for a good CBOR crate in the Rust community, I hope this crate will work for many use-cases.

Deserialization and serialization are prone to logic errors resulting in crashes, from `serde_cbor` I know that it can be useful to fuzz the crate to detect such errors.

**Comment by npmccallum** [comment]
I will be implementing this shortly. Thanks for the suggestion!

**Comment by haraldh** [comment]
So, I tried a quick `cargo-fuzz` implementation with:

```rust
#![no_main]

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let _ = ciborium::de::from_reader::<ciborium::value::Value, _>(data);
});
```

But this panics for every data, which declares an insane value length like:

```rust
#[test]
fn oom_test() {
    let data = vec![91, 20, 20, 20, 20, 20, 20, 20, 20];
    ciborium::de::from_reader::<ciborium::value::Value, _>(&data[..]);
```

It's all about `Vec::with_capacity()` and `Vec::resize()` panicing on OOM.

So, we would have to wait for https://github.com/rust-lang/rust/issues/48043 implementing `Vec::try_reserve()` for this problem.

**Comment by pyfisch** [comment]
@haraldh The solution is to only reserve memory for a small number of items and to dynamically grow the vector if the CBOR document actually contains as many items as claimed by the length field.

If the array size is chosen in such a way that it doesn't crash the program right away but still consumes a large amount of RAM you have an excellent opportunity for DDOS in your internet service.

**Comment by haraldh** [comment]
> If the array size is chosen in such a way that it doesn't crash the program right away but still consumes a large amount of RAM you have an excellent opportunity for DDOS in your internet service.
@pyfisch yes, that's my fear, too

**Comment by npmccallum** [comment]
I'm working on a low level module that should hopefully work for both `alloc` and non-`alloc` cases. In the non-`alloc` case, you specify a scratch buffer. In the `alloc` case, you specify the maximum allocation size. Does this arrangement work for all the cases?

**Comment by pyfisch** [comment]
> In the `alloc` case, you specify the maximum allocation size. Does this arrangement work for all the cases?

It is not sufficient to only specify a maximum allocation size, since there can be large legitimate CBOR documents and ńefarious documents that claim the same size. It is important to only grow the buffer if the elements are actually present and valid.
