### ISSUE TITLE
Remove bignum to 128-bit integer

### ISSUE THREAD

**Issue by pyfisch** [enarx/ciborium#12]
I saw that you convert CBOR bigints to 128-bit integers in Rust. In case the number exceeds 2^128-1, you raise an error. I don't think this is the right approach: For most common tasks 64-bit numbers are more than big enough, but for tasks that use big integers the numbers can easily exceed 128 bits, for example in cryptography.

**Comment by npmccallum** [comment]
@pyfisch I come from the crypto world. So I'm well aware of bignums.

I'm still failing to see the downside of my approach. Serde has no support for bignums. But it does have support for u128/i128. What is the downside in supporting those types?

**Comment by pyfisch** [comment]
@npmccallum My understanding of the code is that all bigints in CBOR are deserialized as 128-bit integer in ciborium. Is that correct?

**Comment by npmccallum** [comment]
@pyfisch That is correct. If this meant that we couldn't deserialize larger bigints, I would agree that we shouldn't do this. But serde doesn't have support for decoding any other kind of bigint.

I propose we do the following:
1. Serialize u128/i128 as bigint(bytes).
2. Serialize BigInt as bytes.
3. Deserialize u128/i128 from any integer type or any bigint(bytes).
4. Deserialize any bytes from bytes or bigint(bytes).

I *think* that covers all the cases.

(Note I make no claim that the current code actually does this correctly.)

**Comment by pyfisch** [comment]
This solution *should* work but I fear that there will be certain edge-cases which exhibit unexpected behavior. From my  perspective the solution is too complicated, instead CBOR bigints should just be exposed as bytes to rust code.

**Comment by npmccallum** [comment]
The strategy in main (and the upcoming release) matches the strategy outlined above. I'm closing this issue and we can address other specific issues when they arise.
