### ISSUE TITLE
[Feature]: is `serde/std` necessary?

### ISSUE THREAD

**Issue by mspiegel** [enarx/ciborium#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the ciborium crate the feature "std" will enable "ciborium-io/std" and "serde/std". Will anything break if the "serde/std" dependency is removed? I cloned the repository, removed "serde/std", and was able to run the tests. My usecase is admittedly strange. I am trying to use the crate [static-regular-grammar](https://github.com/timothee-haudebourg/static-regular-grammar/) in a no_std context. The static-regular-grammar crate provides a derive macro that validates regular grammars. All the macros happen at compile time, which is a std context, so I think I can get away with using the ciborium crate and the "std" feature enabled. However, the ciborium crate with the "std" feature also enables "serde/std". The not-macro part of my build is trying to use serde in a no-std context. And so the compilation fails.

**Comment by jdygert-spok** [comment]
With [`resolver = 2`](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2), build-dependency features should not affect regular dependency features.

**Comment by mspiegel** [comment]
Thank you!
