### ISSUE TITLE
size_hint does not seem to work for SeqAccess

### ISSUE THREAD

**Issue by gh0st42** [enarx/ciborium#17]
I have a custom implementation of `Deserialize` that works with `serde_cbor`, `serde_json`, and others.

In my `visit_seq` function at the beginning I get:
```
[src/primary.rs:91] seq.size_hint() = Some(
    8,
)
```
I then parse a few fields with `.next_element()` and later on check again:
```
[src/primary.rs:118] seq.size_hint() = Some(
    8,
)
```
The number stays the same no matter how often I get a next element.

Usually, the number should decrease, or am I missing something?

**Comment by gh0st42** [comment]
For some more context, the surrounding code looks like this: https://github.com/dtn7/bp7-rs/blob/914ba0b6215344f8fd8415771a35c1f2c579abd4/src/primary.rs#L117

This is the version still on `serde_cbor`, the failing ciborium version can be found here: https://github.com/dtn7/bp7-rs/tree/ciborium

The only difference between the two is that the ciborium version has wrappers to get the old `to_vec` and `from_slice` functions back :)

**Comment by npmccallum** [comment]
@gh0st42 Are you running on master or the latest release? If you're experiencing this against the latest release can you check the master branch?

**Comment by gh0st42** [comment]
Thank you for the quick answer!

I was using the latest release version. 
Due to the use of const generics the master branch needs nightly which is not an option for us :( 

But I just checked if the bug is fixed in the master branch and indeed the bug is not present anymore!
Even though the crate got quite a bit slower in our benchmark (master vs release both on nightly, only encoding since decoding does not run in release :)).

Is the plan for this crate to be nightly-only for the future?

**Comment by npmccallum** [comment]
> But I just checked if the bug is fixed in the master branch and indeed the bug is not present anymore!

Hooray!

> Even though the crate got quite a bit slower in our benchmark (master vs release both on nightly, only encoding since decoding does not run in release :)).

That's interesting. I'm definitely interested in increasing performance. We would gladly accept pull requests that implement benchmarks.

> Is the plan for this crate to be nightly-only for the future?

No. We allowed only the const generics features that are scheduled for release in Rust 1.52. The plan is to roughly correlate our next release with that version of Rust so that nightly isn't required.

**Comment by gh0st42** [comment]
> That's interesting. I'm definitely interested in increasing performance. We would gladly accept pull requests that implement benchmarks.

Mmmh, tests and benchmarks are really missing atm.
What is the preferred form of benchmarks? cargo bench? criterion? custom examples? another way?

Maybe in the future with a bit more time I could extract some of our usecases into more minimal benchmark sets.

**Comment by npmccallum** [comment]
I have opened a separate issue (#26) for benchmarking and speed improvements. I'm closing this issue because it is fixed in main (and the upcoming release).
