### ISSUE TITLE
(Request) an update on serde.rs

### ISSUE THREAD

**Issue by gzp-crey** [enarx/ciborium#20]
Serde.rs still points to the serde_cbor. Based on the maintenance ticket in the other repo this crate seems to be a successor. If it is so and this crate is stable please request an update on the serde page.
At the moment due to the lack of "official" link and   relatively low commit frequency i'm unsure of the stability/long term support of this crate and hence afraid of switching (from bincode)

**Comment by ShadowJonathan** [comment]
serde_cbor is officially discontinued, can this be fast-forwarded please?

**Comment by crapStone** [comment]
done, this can be closed
