### ISSUE TITLE
Update crates.io

### ISSUE THREAD

**Issue by petreeftime** [enarx/ciborium#22]
Is it possible to push an update of this project to crates.io? The version there hasn't been updated in a while and a few features that are useful have been added in the meanwhile, such as tags.

**Comment by anweiss** [comment]
hey @npmccallum, any chance you could provide an update on this?

**Comment by lmammino** [comment]
Upvote for this one.

I was hoping to be able to use the `Value::Tag` variant which does not seem to be supported in the published `0.1.0`...
