### ISSUE TITLE
Using untyped Enum values throws off next value on deserialisation

### ISSUE THREAD

**Issue by MikeCamel** [enarx/ciborium#5]
Consider these two structs:
 `#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum NumberEnum {
    num(u128),
    stringy(String),
    nuffing,
}`
`#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SimpleStructBackend3 {
    pub number: u16,
    pub string: String,
    pub numbenum: NumberEnum,
    pub uuid: Uuid,
}`

Initialising a `SimpleStructBackend3` with `numbenum = NumberEnum::num(42)` or `numberenum = NumberEnum::stringy(String::from("forty-two")` is fine.  Initialising it with `numbenum = NumberEnum::nuffing` causes uuid to fail to deserialise.  No problems found if `numbenum` is the **final** field in `SimpleStructBackend3`.  For some reason, choosing a untyped Enum value causes the **next** field in the struct (`uuid`, in this case) to have the mismatch `Title = Other, Major = Text`, which causes a panic.

**Comment by MikeCamel** [comment]
This happens because when a `Title` has value `pub const NULL: Self = Self(Major::Other, Minor::Immediate(Immediate(22)));` (from `tit.rs`), it is not correctly handled.  Currently trying to work out where it _should_ be handled, and wading through what's going on.

**Comment by MikeCamel** [comment]
Hold on the above.  Now having second thoughts.

**Comment by npmccallum** [comment]
@MikeCamel It might be simplest if you submit a pull request containing a test that fails. It should probably go in `tests/serde.rs`.

**Comment by MikeCamel** [comment]
I have a possible fix.  Doing some testing now.  Not sure it's the _correct_ fix, mind you...

**Comment by MikeCamel** [comment]
[ciborium.rs.txt](https://github.com/enarx/ciborium/files/5629824/ciborium.rs.txt)
